//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestBanksSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BanksSystemEntities : DbContext
    {
        public BanksSystemEntities()
            : base("name=BanksSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bank> Bank { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<DeprtmentsСurrencies> DeprtmentsСurrencies { get; set; }
        public virtual DbSet<Сurrency> Сurrency { get; set; }
    }
}
