//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestBanksSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeprtmentsСurrencies
    {
        public int Id { get; set; }
        public int Currency { get; set; }
        public int Department { get; set; }
        public decimal Buy { get; set; }
        public decimal Sell { get; set; }
    
        public virtual Department Department1 { get; set; }
        public virtual Сurrency Сurrency { get; set; }
    }
}
