//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _10_ModelFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelAddContainer : DbContext
    {
        public ModelAddContainer()
            : base("name=ModelAddContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OfficeAssignment> OfficeAssignmentSet { get; set; }
        public virtual DbSet<Enrollment> EnrollmentSet { get; set; }
        public virtual DbSet<Course> CourseSet { get; set; }
        public virtual DbSet<Department> DepartmentSet { get; set; }
        public virtual DbSet<Person> PersonSet { get; set; }
    }
}
