//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _10_ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficeAssignment
    {
        public string Location { get; set; }
        public string InstructorID { get; set; }
    
        public virtual Instructor Instructor { get; set; }
    }
}
